import java.io.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

public class EjecutableLaboratorio implements MenuOption {

    private static int idAutogenerated = 0;

    public static void main(String[] args) {
        new EjecutableLaboratorio().run();
    }

    @Override
    public void run() {
        //flat para continuar el ingreso de laboratorio
        int choice;

        //array de empleados
        List<Laboratorio> laboratorios = new ArrayList<>();

        do {

            laboratorios.add(
                    new Laboratorio(
                            InputHelper.insertStringByKeyboard("Ingrese nombre del laboratorio... "),
                            InputHelper.insertStringByKeyboard("Ingrese domicilio del laboratorio... "),
                            InputHelper.insertStringByKeyboard("Ingrese telefono del laboratorio... "),
                            InputHelper.insertIntByKeyboard("Ingrese la compra minima ... "),
                            InputHelper.insertIntByKeyboard("Ingrese dia de entrega ... ")
                    )
            );

            choice = InputHelper.insertIntByKeyboard("Ingrese 1 si desea agregar otro empleado o 0 si desea salir....");

        } while (choice != 0);

        try (DataOutputStream dataOutputStream = new DataOutputStream(new FileOutputStream("Laboratorio.dat"))) {

            for (Laboratorio i_laboratorio : laboratorios) {
                this.writeLaboratorio(i_laboratorio, dataOutputStream);
            }

        }catch (Exception e){
            e.printStackTrace();
        }
    }


    private void writeLaboratorio(Laboratorio p_laboratorio, DataOutputStream p_dataOutputStream) throws IOException {
        p_dataOutputStream.writeInt(idAutogenerated++);
        p_dataOutputStream.writeUTF(p_laboratorio.getNombre());
        p_dataOutputStream.writeUTF(p_laboratorio.getDomicilio());
        p_dataOutputStream.writeUTF(p_laboratorio.getTelefono());
        p_dataOutputStream.writeInt(p_laboratorio.getCompraMinima());
        p_dataOutputStream.writeInt(p_laboratorio.getDiaEntrega());
    }
}
